var ptLogin_callBack;function initVote(a){var b=$(".vote"),c="vote_"+b.length;b.get(b.length-1).id=c;tips.init();(new voteHandle(c,a)).init()}function voteHandle(a,b){this.id=a;this.type=b}
voteHandle.prototype={init:function(){var a=this;this.voteId=$("#"+this.id).attr("data");"1"==this.type?$("#"+this.id+" ul li .link").bind("click",function(){a.getContent(0)}):"2"==this.type?$("#"+this.id+" .vote-result .link").each(function(b){$(this).bind("click",function(){a.getContent(b)})}):$("#"+this.id+" .vote-list .link").each(function(b){$(this).bind("click",function(){a.getContent(b)})})},getContent:function(a){var b=this;this.index=a;$.ajax({type:"GET",dataType:"json",success:function(a){b.cb(a)},
url:"/g/s?aid=news_js",data:{sid:sid,mst:"27",voteId:b.voteId,vote:a+1}})},cb:function(a){0!=a.result?tips.showTip('<div class="error-tips">'+a.msg+"</div>",!0):(tips.showTip('<div class="seccess-tips">'+a.msg+"</div>",!0),1==this.type?-1==$("#"+this.id+" .vote-list span").text().indexOf("%")&&(a=parseInt($("#"+this.id+" .vote-list span").text()),$("#"+this.id+" .vote-list span").text(a+1)):2==this.type?-1==$("#"+this.id+" span").get(this.index).innerText.indexOf("%")&&(a=parseInt($("#"+this.id+" span").get(this.index).innerText),
$("#"+this.id+" span").get(this.index).innerText=a+1):-1==$("#"+this.id+" .vote-list li").get(this.index).children[1].innerText.indexOf("%")&&(a=parseInt($("#"+this.id+" .vote-list li").get(this.index).children[1].innerText),$("#"+this.id+" .vote-list li").get(this.index).children[1].innerText=a+1))}};function initNewVote(a){var b=$(".mod-vote-container"),c="mod-vote-container_"+b.length;b.get(b.length-1).id=c;a=new voteHandleNew(c,a);tips.init();a.init()}
function voteHandleNew(a,b){this.id=a;this.type=b}
voteHandleNew.prototype={init:function(){var a=this;this.voteId=$("#"+this.id).attr("data");"0"==this.type?$("#"+this.id+" ul li span").bind("click",function(b){a.SingleVote(this)}):"1"==this.type&&($("#"+this.id+" ul li input").bind("click",function(b){a.checkVote(this)}),$("#"+this.id+" .mod-txt-list5 .vote-tips").bind("click",function(b){a.MoreVote(this)}))},SingleVote:function(a){var b=this;this.voteIndex=$(a).attr("data");this.index=$(a).attr("index");$.ajax({type:"GET",dataType:"json",success:function(a){b.cb(a,
b.index)},url:"/g/s?aid=news_js",data:{sid:sid,mst:"27",voteId:b.voteId,vote:b.voteIndex}})},checkVote:function(a){var b=this;b.sel=0;b.total=0;$("#"+b.id+" ul li input").each(function(){b.total++;!0==$(this)[0].checked&&b.sel++});if(10<b.sel)return a.checked=!1,alert("最多选择十个选项");0==b.sel?($("#"+b.id+" .mod-txt-list5 .vote-tips").removeClass("c-tx6"),$("#"+b.id+" .mod-txt-list5 .vote-tips").html("请选择")):($("#"+b.id+" .mod-txt-list5 .vote-tips").addClass("c-tx6"),$("#"+b.id+" .mod-txt-list5 .vote-tips").html("投票("+
b.sel+"/"+b.total+")"))},MoreVote:function(a){if("请选择"!=a.innerHTML){var b=this;b.voteIndex="";b.index="";$("#"+b.id+" ul li input").each(function(){b.total++;!0==$(this)[0].checked&&(b.voteIndex+=$(this).attr("data")+";",b.index+=$(this).attr("index")+";")});b.voteIndex=b.voteIndex.substr(0,b.voteIndex.length-1);b.index=b.index.substr(0,b.index.length-1);$.ajax({type:"GET",dataType:"json",success:function(a){b.cb(a,b.index)},url:"/g/s?aid=news_js",data:{sid:sid,mst:"27",voteId:b.voteId,vote:b.voteIndex}})}},
cb:function(a,b){if(0!=a.result)tips.showTip('<div class="error-tips">'+a.msg+"</div>",!0);else{$("#"+this.id+" .mod-txt-list5").hide();for(var c=b.split(";"),d=0;d<c.length;d++)$($("#"+this.id+" .mod-txt-list7 li")[c[d]]).append('<div class="icon-checked-show"></div>');$("#"+this.id+" .mod-txt-list7 .vote-tips").html("投票成功");$("#"+this.id+" .mod-txt-list7").show()}}};
function initXinGeBangVote(){var a=$(".list-music-image"),b="xingebang_"+a.length;a.get(a.length-1).id=b;tips.init();(new xinGeBangHandle(b)).init()}function xinGeBangHandle(a){this.id=a}
xinGeBangHandle.prototype={init:function(){var a=this;this.voteId=$("#"+this.id).attr("data");$("#"+this.id+" .u-list .ilike").each(function(b){var c=$(this).attr("vote");$(this).bind("click",function(){$(this).addClass("active");a.getContent(b,c)})})},getContent:function(a,b){var c=this;this.index=a;this.vote=b;$.ajax({type:"GET",dataType:"json",success:function(a){c.cb(a)},url:"/g/s?aid=news_js",data:{sid:sid,mst:"31",voteId:c.voteId,vote:b}})},cb:function(a){0!=a.result&&-3!=a.result?(tips.showTip('<div class="error-tips">'+
a.msg+"</div>",!0),$("#"+this.id+" .u-list li").get(this.index).lastChild.className="ilike"):-3==a.result?($("#"+this.id+" .u-list li").get(this.index).lastChild.className="ilike",onLogin()):(tips.showTip('<div class="seccess-tips">'+a.msg+"</div>",!0),-1==$("#"+this.id+" .u-list li").get(this.index).lastChild.innerText.indexOf("%")&&(a=parseInt($("#"+this.id+" .u-list li").get(this.index).lastChild.innerText),$("#"+this.id+" .u-list li").get(this.index).lastChild.innerText=a+1),$("#"+this.id+" .u-list li").get(this.index).lastChild.className=
"ilike disable")}};var tips={init:function(){var a;a='<div class="txt-tips" id="commentTip"><div class="seccess-tips"><span>发送成功</span></div></div>';0==$("#commentTip").length&&$("body").append(a)},showTip:function(a,b){var c=this;$("#commentTip").html(a);var d=document.body.scrollTop+document.documentElement.scrollTop;$("#commentTip").css("top",d+"px");b&&setTimeout(function(){c.hiddenTip()},2E3)},hiddenTip:function(){$("#commentTip").css("top","-36px")}};
function initSubcribeChannel(a){tips.init();VANGOGH.loginMod.init(window.sid,window.islong3g,-123456);var b=0,c=function(){window.sid||location.search.match(/sid=[^&]*/);$.ajax({url:"http://infoapp.3g.qq.com/g/usercenter/touch/api/api.jsp?sid="+VANGOGH.loginMod.getSid()+"&action=booking&op=add&book_pos="+a+"&callback=?",dataType:"jsonp",success:function(a){3<=b||(a.booking?-1==a.booking.status?VANGOGH.loginMod.login(c):1==a.booking.status?(tips.showTip('<div class="seccess-tips">订阅成功，<a href="http://infoapp.3g.qq.com/g/usercenter/touch/?sid='+
VANGOGH.loginMod.getSid()+'"  style="color:#fff">点击查看</a></div>',!0),$("#subcribe-channel").hide()):(tips.showTip('<div class="error-tips">订阅失败</div>',!0),b++):tips.showTip('<div class="error-tips">发生错误</div>',!0))},error:function(){}})};$(function(){$("#subcribe-channel").bind("click",c)})}var user_callBack;
ptLogin_callBack=function(a){console.log(a);VANGOGH.loginMod._sid=a.sid;VANGOGH.loginMod._uid=a.uin;VANGOGH.loginMod._islogin=!0;if(a=document.getElementById("footer-login"))a.innerHTML="退出";user_callBack()};
VANGOGH.loginMod={_sid:"",_islogin:!1,init:function(a,b,c){this._sid=a;this._islogin=b;this._uid=c},getSid:function(){return this._sid},login:function(a){user_callBack=a||function(){};this._islogin?user_callBack():"undefined"!=typeof ptLogin&&ptLogin?ptLogin.login(function(a){ptLogin_callBack(a)}):loadScript("http://3gimg.qq.com/wap30/libs/login/ptLogin_info_v20141128.js",function(){ptLogin.login(function(a){ptLogin_callBack(a)})})},isLogin:function(){return this._islogin},getUid:function(){return this._uid}};
var loginModule=VANGOGH.loginMod;function initNewComment(a,b,c,d,e){var g=$(".template_comment_div"),h="template_comment_div_"+g.length;g.get(g.length-1).id=h;var f={};f.index=g.length;f.obj=$("#"+h);f.id=a;f.boardid=e;f.sid=b;f.uid=c;f.commenturl="http://comment.3g.qq.com/g/s?aid=cmt_addFromss&id="+f.id+"&sid="+f.sid;f.islogin=d;a=new CommentBox;a.init(f);a.fetch();loginModule.init(f.sid,f.islogin,f.uid);tips.init()}
var CommentBox=function(){this.init=function(a){this.obj=a.obj||null;this.callbacks=a.callbacks||{};this.id=a.id;this.sid=a.sid;this.boardid=a.boardid;this.commenturl=a.commenturl;this.index=a.index;this.pn=1;this.loadedNums=0;this.obj.html('<div class="info-comment">   <div class="info-comment-reply">       <textarea class="info-reply-area cmt_text" placeholder="生活很无聊，何不来吐槽" id="cmt_textarea"></textarea>       <div class="info-reply-bar info-bar  hide">           <div class="comment-count t_join_count"></div>           <button class="info-btn info-btn-submit t_send">发表</button>       </div>   </div>'+
('<div class="main-comment hot-comment">   <ul class="main-comment-list t_top_cmt_dl" style="display: none">   </ul><div class="comment-link-more" id="more-comment-'+this.index+'" style="display:none"><a href=\''+this.commenturl+"'>全部评论</a></div></div>")+"</div>");this._bindClick();this.callbacks.init&&this.callbacks.init()};this.setCount=function(a,b){$(".t_latest_more_words").text("更多评论"+(b-this.loadedNums)+"条");$(".t_latest_end_words").text("共"+b+"条评论");$(".t_join_count").html(parseInt(a)?a+"人参与评论":
"暂无评论")};this.fetch=function(){var a=this;$.ajax({url:"http://infoapp.3g.qq.com/g/s?aid=cmt_touch_api&callback=?&dt=cmtLst&cmtId="+a.boardid+"&pn=1&ps=10&pkuName=infonews&cmtType=0",dataType:"jsonp",success:function(b){console.log(b);a._fetchSuccess(b.cmtLst)}})};this._fetchSuccess=function(a){var b=a.parentcmts,c=a.hot.record,c=c.slice(0,3),d=a.latest.record;0<d.length&&(d=d.slice(0,5-c.length));c=c.concat(d);0<c.length&&$(this.obj).find(".t_top_cmt_dl").html(this._rendercmtLst(c,b)).show();this.setCount(a.allcount||
0,a.cmtcount||0);this.callbacks.update&&this.callbacks.update(a.cmtcount||0)};this._rendercmtLst=function(a,b){if(a)for(var c="",d,e=0;e<a.length;e++)d=a[e],c+='<li>   <a class="comment-list-title">       <strong class="comment-user-name">           <span class="t_ucc_link" uid="'+d.userid+'">'+d.usernick+'</span>       </strong>       <time class="'+(1==d.hot?"ihot":"")+'">'+formatTimeToNow(d.timestamp)+"</time>   </a>",c+='   <div class="comment-content">'+d.shortcontent+"</div></li>";return c};
this._doCmt=function(){var a=this,b=decodeURIComponent(this.obj.find(".cmt_text").val());b?$.ajax({url:"http://infoapp.3g.qq.com/g/s?aid=cmt_touch_api&callback=?&"+$.param({dt:"cmtOp",comment:b,title:encodeURIComponent(document.title),url:encodeURIComponent(location.href),entityId:encodeURIComponent(a.id),pkuName:"infonews",cmtType:"0",cmtId:a.boardid}),dataType:"jsonp",success:function(c){"-10"==c.result?loginModule.login(function(){a._doCmt()}):0==c.result?(c='<li>   <a class="comment-list-title">       <strong class="comment-user-name">           <span class="t_ucc_link" uid="">我</span>       </strong>       <time>刚刚</time>   </a>   <div class="comment-content">'+
b+"</div></li>",tips.showTip('<div class="seccess-tips">操作成功</div>',!0),$("#cmt_textarea").css("height","54px"),$(".info-bar").hide(),$(a.obj).find(".t_top_cmt_dl").prepend(c).show(),a.obj.find(".cmt_text").val(""),c=parseInt(a.obj.find(".comment-count").text()||"0")+1,a.callbacks.post&&a.callbacks.post(c)):tips.showTip('<div class="error-tips">系统繁忙，请重试!</div>',!0)}}):tips.showTip('<div class="seccess-tips">请输入评论内容!</div>',!0)};this._bindClick=function(){var a=this;$(a.obj).delegate(".t_send","click",
function(){loginModule.login(function(){a._doCmt()})});$(a.obj).delegate(".t_ucc_link","click",function(){var a=loginModule.getSid();encodeURIComponent($(this).attr("uname"));var c=loginModule.getUid(),d=$(this).attr("uid")||c;location.href="http://infoapp.3g.qq.com/g/usercenter/touch/?sid="+a+"&uin="+d+"#"+(c==d?"home":"hishome")});$(a.obj).delegate(".cmt_text","click",function(){$(".info-bar").css("display"," -webkit-box");$(this).css("height","78px")})};this.clear=function(){this.pn={hot:1,latest:1};
this.loadedNums=0;$(this.obj).find(".t_top_cmt_dl,.t_hot_cmt_dl,.t_latest_cmt_dl").html("");$(this.obj).find(".t_latest_more,.t_latest_more_end").hide()}};
function formatTimeToNow(a){if(!isNumber(a))return a;var b=new Date,c=new Date(parseInt(a));a=b.getTime()-a;return 5184E5<a?c.getFullYear()!==b.getFullYear()?c.getFullYear()+"年"+(c.getMonth()+1)+"月"+c.getDate()+"日":c.getMonth()+1+"月"+c.getDate()+"日":864E5>a?6E4>a?Math.floor(a/1E3)+"秒前":36E5>a?Math.floor(a/6E4)+"分钟前":Math.floor(a/36E5)+"小时前":1728E5>a?(b=36E5*b.getHours()+864E5,a<b?"昨天":"前天"):Math.ceil(a/864E5)+"天前"}
function formatDigi(a){a=parseInt(a);1E4<a&&(a=(a/1E4).toFixed(1)+"万",a=a.replace(".0",""));return a}function isNumber(a){return"[object Number]"===Object.prototype.toString.call(a)}
function loadScript(a,b){try{a=a instanceof Array?a:[a];b=b instanceof Array?b:[b];var c=document.getElementsByTagName("head")[0],d=document.createDocumentFragment(),e=[];$.each(a,function(a,b){e[a]=document.createElement("script");e[a].src=b;e[a].type="text/javascript";d.appendChild(e[a])});c.appendChild(d);$.each(b,function(a,b){"function"==typeof b&&(e[a].onreadystatechange=function(){("complete"==e[a].readyState||"loaded"==e[a].readyState)&&b()},e[a].onload=function(){b()},e[a].onerror=function(){this.onload=
this.onerror=null;this.parentNode.removeChild(this)})})}catch(g){console.error("Warning:There is error on load javascript file!")}};

/*FEND*/